{"name": "test_getUserInfo[18682115996]", "status": "broken", "statusDetails": {"message": "requests.exceptions.InvalidSchema: No connection adapters were found for 'api/live/app/getUserInfohttps://radio-api-demo.zlzgy.org.cn/'", "trace": "self = <TestCase.test_getInfo.TestGetInfo object at 0x1041ad0d0>\nmibole = '18682115996'\n\n    @allure.severity('blocker')\n    @allure.story(\"测试获取用户信息\")\n    @pytest.mark.parametrize(\"mibole\", [\"18682115996\"])\n    def test_getUserInfo(self,mibole):\n>       a=getInfo.getUserInfo(mibole)\n\nTestCase/test_getInfo.py:17: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \napi/getInfo.py:15: in getUserInfo\n    self.json_data= requests.post(self.info_url+self.url,headers=self.headers,verify = False,json={\"mobile\":mobile}).json()\n/usr/local/lib/python3.7/site-packages/requests/api.py:116: in post\n    return request('post', url, data=data, json=json, **kwargs)\n/usr/local/lib/python3.7/site-packages/requests/api.py:60: in request\n    return session.request(method=method, url=url, **kwargs)\n/usr/local/lib/python3.7/site-packages/requests/sessions.py:533: in request\n    resp = self.send(prep, **send_kwargs)\n/usr/local/lib/python3.7/site-packages/requests/sessions.py:640: in send\n    adapter = self.get_adapter(url=request.url)\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <requests.sessions.Session object at 0x1041a7d50>\nurl = 'api/live/app/getUserInfohttps://radio-api-demo.zlzgy.org.cn/'\n\n    def get_adapter(self, url):\n        \"\"\"\n        Returns the appropriate connection adapter for the given URL.\n    \n        :rtype: requests.adapters.BaseAdapter\n        \"\"\"\n        for (prefix, adapter) in self.adapters.items():\n    \n            if url.lower().startswith(prefix.lower()):\n                return adapter\n    \n        # Nothing matches :-/\n>       raise InvalidSchema(\"No connection adapters were found for '%s'\" % url)\nE       requests.exceptions.InvalidSchema: No connection adapters were found for 'api/live/app/getUserInfohttps://radio-api-demo.zlzgy.org.cn/'\n\n/usr/local/lib/python3.7/site-packages/requests/sessions.py:731: InvalidSchema"}, "parameters": [{"name": "mibole", "value": "'18682115996'"}], "start": 1574930881517, "stop": 1574930881518, "uuid": "9785f09d-2c4d-42e0-8a94-1a06c6a836d1", "historyId": "024afde7f204345f563268fea6d34133", "fullName": "TestCase.test_getInfo.TestGetInfo#test_getUserInfo[18682115996]", "labels": [{"name": "story", "value": "测试获取用户信息"}, {"name": "severity", "value": "blocker"}, {"name": "parentSuite", "value": "TestCase"}, {"name": "suite", "value": "test_getInfo"}, {"name": "subSuite", "value": "TestGetInfo"}, {"name": "host", "value": "xiaomaideMacBook-Pro.local"}, {"name": "thread", "value": "18006-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "TestCase.test_getInfo"}]}